Source/Sync.m, Tests/Tests.xcodeproj/project.pbxproj, Tests/Tests/Model.xcdatamodeld/Demo.xcdatamodel/contents, Tests/Tests/Tests.m, Tests/Tests/numbers_in_collection.json
get correct EntityName for relationship
=> relationship entity name fix

README.md
=> Add to README how to filter synced elements

Tests/Tests.xcodeproj/project.pbxproj, Tests/Tests/JSONs/bug-number-84.json, Tests/Tests/Models/Bug84.xcdatamodeld/.xccurrentversion, Tests/Tests/Models/Bug84.xcdatamodeld/Demo.xcdatamodel/contents, Tests/Tests/Tests.m
Fixes #84
The bug was probably fixed on the last release of HYPPropertyMapper, didn't found anything.
=> Fix: bug 84

Tests/Tests/JSONs/comments-no-id.json, Tests/Tests/Tests.m
Just improved tests to check for more things.
=> Improve tests

Tests/Tests/Tests.m
Cleanup proposal.If you agree can cleanup further. 
Counting and fetching should go to some base method.
=> Cleanup fetching and count

Examples/DesignerNews/DesignerNews/DesignerNews.xcdatamodeld/DesignerNews.xcdatamodel/contents
A comment has many comments but to work properly it also needs to state
a parentComment.
=> Add parentComment to Comment entity

Source/Sync.m, Tests/Tests/Tests.m
=> Improve usage of predicate

.travis.yml, README.md, Tests/Tests/Tests.m
=> Add FAQ about logging

Tests/Podfile.lock, Tests/Tests.xcodeproj/project.pbxproj, Tests/Tests/JSONs/patients.json, Tests/Tests/Models/Patients.xcdatamodeld/.xccurrentversion, Tests/Tests/Models/Patients.xcdatamodeld/Demo.xcdatamodel/contents, Tests/Tests/Tests.m
Sync is working fine, the only thing that seems to be missing is `Fitness`, `Alcohol` and `Weight` printing their measures. This is because `hyp_dictionary` is not recursive, it just prints `childs` up to one level. I opened an issue for that, but that was expected behaviour. https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/issues/82
=> [Demo purposes]: Patient 

Source/Sync.m, Tests/Podfile.lock, Tests/Tests.xcodeproj/project.pbxproj, Tests/Tests.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme, Tests/Tests/JSONs/bug-125.json, Tests/Tests/Models/Bug125.xcdatamodeld/.xccurrentversion, Tests/Tests/Models/Bug125.xcdatamodeld/Demo.xcdatamodel/contents, Tests/Tests/Tests.m
```json
{
"uri":"http://tempuri.org/any/path/mydescriptor/1.2?language=en-US",
"type":"http://tempuri.org/any/path/mydescriptor/",
"version":"1.2",
"language":"en-US",
"element":{
"type":"group",
"label":"Any Form",
"elements":[
{
"type":"input",
"label":"Any Input",
"reference":"anyInteger",
"inputConfiguration":{
"justAHint":[
"a",
"b",
"c"
]
}
},
{
"type":"group",
"label":"Any Group",
"elements":[
{
"type":"selectSingle",
"label":"Any Single Select",
"reference":"anyString",
"selection":"closed",
"items":[
{
"value":"option1",
"label":"Option One"
},
{
"value":"option2",
"label":"Option Two"
}
]
},
{
"type":"selectMultiple",
"label":"Any Multiple Select",
"reference":"anyString",
"selection":"open",
"items":[
{
"value":"option3",
"label":"Option Three",
"aliasLabels":[
{ …
```
=> Fix: bug #125

README.md
I'm a book author just noticing some little typos--but let me know if you need any other English documentation help, for punching up the language
=> Small grammar fixes for README.md

Demo.xcodeproj/project.pbxproj, Source/NSManagedObject+Sync.m, Source/Sync.m, Tests/JSONs/notes_with_user_id.json, Tests/JSONs/tagged_notes.json, Tests/Models/Notes.xcdatamodeld/Demo.xcdatamodel/contents, Tests/SyncTests.m
=> Feature: Sync relationships using id

AppNet/Networking.swift, AppNet/ViewController.swift
This shows an example on how to use change notifications, useful for logging and to react to changes in your database.
=> Improve change notifications

README.md
The current code snippet does not include the NSError parameter in the completion block. I corrected it by adding the NSError parameter to the completion block.
=> Correct the code snippet in the "Sync" section

Demo.xcodeproj/project.pbxproj, Source/NSManagedObject+Sync.h, Source/NSManagedObject+Sync.m, Tests/NSManagedObject+Sync_Tests.swift
=> Skip changes if incoming change doesn't change things

AppNet/Networking.swift, Podfile
Modified Appnet example to use alamofire. added alamofire to podfile.
=> Modified AppNet Example to use Alamofire 

Demo.xcodeproj/project.pbxproj, Source/NSArray+Sync.swift, Source/NSEntityDescription+Sync.swift, Source/NSManagedObject+Sync.swift, Source/NSManagedObjectContext+Sync.swift, Source/Sync.swift, Tests/NSManagedObject+SyncTests.swift, Tests/SyncTests.swift
=> Improve documentation

Demo.xcodeproj/project.pbxproj, Podfile.lock, Source/NSManagedObject+Sync.swift, Tests/JSONs/bug-202-a.json, Tests/JSONs/bug-202-b.json, Tests/JSONs/bug-202-c.json, Tests/Models/Bug202.xcdatamodeld/.xccurrentversion, Tests/Models/Bug202.xcdatamodeld/Demo.xcdatamodel/contents, Tests/SyncTests.swift
=> Fix bug 202

README.md
=> Add "How to map relationships that don't have remote IDs?" to FAQ

Podfile.lock, Sync.podspec
=> Update DATAFilter dependency

Demo.xcodeproj/project.pbxproj, Source/NSManagedObject+Sync.swift, Tests/JSONs/bug-257.json, Tests/Models/Bug257.xcdatamodeld/Bug179.xcdatamodel/contents, Tests/SyncTests.swift
=> Fix: bug 257

Demo.xcodeproj/project.pbxproj, Tests/Sync/JSONs/233-order-a.json, Tests/Sync/JSONs/233-order-b.json, Tests/Sync/Models/233.xcdatamodeld/233.xcdatamodel/contents, Tests/Sync/SyncTests.swift
I created a test case for the ordering issue named in #233. The test fails at the moment but I think shows the issue. 
The test only contains synced ids, not synced dictionaries. Maybe those should be tested as well. Futhermore, in this test are no new items added, existing ones are just re-ordered.  
Maybe someone has a proper solution to fix the issue by using this test case.
=> Added test case for #233

Demo.xcodeproj/project.pbxproj, Source/Sync/NSManagedObject+Sync.swift, Source/Sync/Sync.swift, Tests/Sync/NSPersistentContainerTests.swift, Tests/Sync/SyncDelegateTests.swift
=> Reuse generic method for NSOperation

Source/Sync/Sync.swift, Tests/Sync/DeleteTests.swift, Tests/Sync/InsertOrUpdateTests.swift
Remove the completion and use throw instead
=> Remove helper methods

Source/Sync/NSManagedObject+Sync.swift, Source/Sync/Sync.swift
Many completions were used where throws made more sense. Specially code that wasn't async.
=> Changed a few completions for throws

Demo.xcodeproj/project.pbxproj, Source/Sync/Sync.swift, Tests/Sync/UpdateTests.swift
```swift
try! Sync.update("id", with: ["name": "bossy"], inEntityNamed: "User", using: dataStack.mainContext)
```
=> Add helper method for update

Source/Sync/Sync+NSPersistentContainer.swift, Tests/Sync/FetchTests.swift, Tests/Sync/Helpers/Helper.swift, Tests/Sync/NSPersistentContainerTests.swift
Fixes https://github.com/SyncDB/Sync/issues/344
=> Improve NSPersistentContainer extension methods

Demo.xcodeproj/project.pbxproj, Tests/Sync/JSONs/356.json, Tests/Sync/Models/356.xcdatamodeld/.xccurrentversion, Tests/Sync/Models/356.xcdatamodeld/Demo.xcdatamodel/contents, Tests/Sync/SyncTests.swift
```json
[
{
"id": "store_1",
"store_products": [
{
"id": "store_product_1",
"store_id": "store_1",
"product_id": "product_1"
}
]
}
]
```
=> Example of 356

Source/DataFilter/DataFilter.swift, Tests/DataFilter/DataFilterTests.swift
Includes changes in https://github.com/SyncDB/Sync/pull/378 but without the merge conflict.
=> Improve filter performance

Source/Sync/Sync.swift
Closes https://github.com/3lvis/Sync/issues/366
=> #366: Fix operation is never marked as finished

Source/DataStack/DataStack.swift
Fixes https://github.com/3lvis/Sync/issues/437
=> Fix completion returning after each store is dropped

Project.xcodeproj/project.pbxproj, Tests/Sync/JSONs/449.json, Tests/Sync/Models/449.xcdatamodeld/449.xcdatamodel/contents, Tests/Sync/SyncTests.swift
Hi @3lvis ,
I found some time and made a pull request for issue 449: https://github.com/3lvis/Sync/issues/449
I hope I got everything right in your test environment.
Greetings, Max
=> Added test for issue 449.

Project.xcodeproj/project.pbxproj, Tests/Sync/JSONs/custom_relationship_key_to_one.json, Tests/Sync/JSONs/jimijonProducts.json, Tests/Sync/JSONs/jimijonSubcategories.json, Tests/Sync/JSONs/remote_key.json, Tests/Sync/Models/jimijon.xcdatamodeld/TestOneToOneToOne.xcdatamodel/contents, Tests/Sync/SyncTests.swift
Create a test for the to-one-to-one reference becoming nil when staging the syncs.
=> jimijon tests

Source/Sync/NSManagedObject+Sync.swift
=> Fix crash in to-many relationship

Source/PropertyMapper/NSManagedObject+PropertyMapperHelpers.m
Tried adding unit tests but it isn’t possible since this feature is iOS 11 and above
=> Add support for UUID inserting and exporting

Source/DataStack/DataStack.swift
https://github.com/3lvis/DATAStack/pull/112
=> Annotate background context

Project.xcodeproj/project.pbxproj, Source/PropertyMapper/PropertyMapper.m, Tests/PropertyMapper/ExportTests.swift, Tests/PropertyMapper/Models/482.xcdatamodeld/482.xcdatamodel/contents
Fixes [Issue-482](https://github.com/3lvis/Sync/issues/482) flattened objects not exporting in nested format.
=> fixes issue 482 flattened keys not exporting in nested format properly.

Source/DataStack/DataStack.swift, circle.yml
https://developer.apple.com/library/content/qa/qa1809/_index.html
https://github.com/3lvis/Sync/issues/490
=> Update journaling mode

Source/DateParser/NSDate+PropertyMapper.m, Tests/DateParser/DateTests.swift
=> Add support for deciseconds

Source/Sync/Sync+NSManagedObjectContext.swift
=> add optional operations argument

Source/DataStack/DataStack.swift, Tests/DataFilter/DataFilterTests.swift, Tests/DataStack/Tests.swift, Tests/Sync/Helpers/Helper.swift, Tests/Sync/NSManagedObjectContext+SyncTests.swift
=> Optional initializer
