Source/Sync.m
Rather than the previous process that only used the actual attribute for the local key, this now uses the actual primary attribute (either the marked attribute or the default remoteID attribute) and pulls out the provided remote key. 
Unfortunately this doesn't add additional tests for this case. 
Fixes #58.
=> update local and remote key handling for entities

Source/Sync.m, Tests/Tests/Model.xcdatamodeld/Demo.xcdatamodel/contents, Tests/Tests/Tests.m, Tests/Tests/users_notes.json
Before, if you had any relationship whose name contained more than a single word, such as "profilePictures", Sync would try to fetch the key "profilePictures" from the JSON dictionary, instead of trying the key "profile_pictures".
This pull request fixes this issue and add a test case for this.
=> Make it so the relationships name are correctly converted to the corresponding JSON name

Source/Sync.h, Source/Sync.m
I found myself having to use some private methods you use in Sync:
- For getting the remote key and the local key of a NSManagedObject
- For processing the relationships on a NSManagedObject (In case you have a dictionary of a single object, that you would to merge into an existing object including the relationships)
=> Expose some utility methods so that they can be used by anybody

Source/Sync.m, Tests/Tests/Model.xcdatamodeld/Demo.xcdatamodel/contents, Tests/Tests/Tests.m, Tests/Tests/users_notes.json
Allow the mapping of one-to-one relationships that do not have a remoteID (This fixes the crash that was happening in that case)
This pull request also add the mapping of relationships of object resulting from a one-to-one relationship which was missing.
This is especially helpful in case you have a CoreData object that contains common properties (i.e., an Image object that contains both a thumbnail and a full image URL, which could be stored as part of every other object)
=> Improve one-to-one relationships mapping

Source/NSManagedObject+Sync.m, Source/Sync.m, Tests/Tests/Tests.m
Switching to SQLite mode triggered many errors, this PR hopefully fixes all of them.
- Switched to SQLite mode
- Removed .sqlite file before creating new one
- Fixed errors
- Went back to InMemory mode
Using custom primary keys on a many-to-many relationship is still a known issue.
=> Fix: SQLite mode errors

.travis.yml, Source/NSEntityDescription+Sync.h, Source/NSEntityDescription+Sync.m, Source/NSManagedObject+Sync.h, Source/NSManagedObject+Sync.m, Source/Sync.m, Tests/Tests.xcodeproj/project.pbxproj, Tests/Tests/JSONs/organizations-tree.json, Tests/Tests/Models/Organizations.xcdatamodeld/Organizations.xcdatamodel/contents, Tests/Tests/Tests.m
The root organization has a `parentUnit = nil` that isn't taken into account when filtering the changes
Sync should check if the entity been synced has a parent entity and add it to the predicate:
Predicate: `parentUnit = nil` for root objects 
otherwise it will fetch all organizations, even the ones with parents
I pushed a silly fix
=> Fix: recursive sync

Source/NSManagedObject+Sync.m
Here is a proposed change that fixes #140 
An object that is referenced with "{model}_id"  will be related if it exists in Core Data
=> Added feature to sync relationships with only ID

Demo.xcodeproj/project.pbxproj, Demo.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme, Source/NSArray+Sync.swift, Source/NSEntityDescription+Sync.swift, Source/NSManagedObject+Sync.swift, Source/NSManagedObjectContext+Sync.swift, Source/Sync.swift
I was bored and couldn't sleep so this happened. I thought that `Sync` could use a bit of Swift lovin.
I saw that we had a nack for force unwrapping optional values and that the implementation did not conform to our guidelines. This PR is an attempt to correct those faulty thingies.
As an added bonus; code coverage is now enabled in the Xcode project :rocket: 
- Use forEach instead of for-loop
- Remove redundant isKindClass check
- Fix indentation
- [Use filter instead of for-loop with if statement](https://github.com/hyperoslo/Sync/blob/feature/modern-implementation/Source/NSEntityDescription%2BSync.swift#L25-L27)
- Remove unnecessary object declaration
- Improve readability of valid class comparison
- Use forEach instead of for-loop
- Remove force unwrapping of objects when type casting …
=> Modernize implementation.

Demo.xcodeproj/project.pbxproj, Podfile.lock, Sync.podspec, Tests/JSONs/id.json, Tests/Models/id.xcdatamodeld/.xccurrentversion, Tests/Models/id.xcdatamodeld/Demo.xcdatamodel/contents, Tests/SyncTests.swift
`id` wasn't considered in the first round because is a reserved word on Objective-C, in Swift it isn't. 💥 
I have kept the old `remoteID` for compatibility reasons, although I'll update everything to mention `id` as the preferred way.
=> Add support to use id as primary key

Podfile.lock, Source/NSManagedObject+Sync.swift, Source/Sync.swift, Sync.podspec
The previous change certainly improves things in a way since it will save less frequently and sends less notifications but it breaks when using NSFetchedResultsControllers since it doesn't merge all the notifications.
=> Remove "performance" improvement

Source/NSManagedObject+Sync.swift, Tests/JSONs/151-many-to-many-notes-update.json, Tests/JSONs/151-many-to-many-notes.json, Tests/SyncTests.swift
Add support for cleaning up many to many relationships using `null` in the JSON object.
=> cleaning up id only many to many using null

Demo.xcodeproj/project.pbxproj, README.md, Source/NSArray+Sync.swift, Source/NSManagedObject+Sync.swift, Source/Sync.swift, Tests/JSONs/operation-types-users-a.json, Tests/JSONs/operation-types-users-b.json, Tests/SyncTests.swift
```swift
let firstImport = // First import of users
Sync.changes(firstBatch, inEntityNamed: "User", dataStack: dataStack, operations: [.All]) {
// All users have been imported, they are happy 
}
// Likely after some changes have happened, here usually Sync would remove the not found items
let secondImport = // Second import of users
Sync.changes(secondImport, inEntityNamed: "User", dataStack: dataStack, operations: [.Insert, .Update]) {
// Here new users have been imported, existing users have been updated, and not found users have been ignored
}
```
=> Add basic support for operation types

Source/Sync.swift
The problem described in #230 can be easily resolved by making an `internal` method `public`. That PR is doing just that.
=> Allow to set operations when using specific context

Source/NSManagedObject+Sync.swift
The entity in sync_toManyRelationship was referencing the parent entity instead of the destination entity. This is was the reason for the uncaught exception as referenced in the following open issues:
https://github.com/hyperoslo/Sync/issues/272
https://github.com/hyperoslo/Sync/issues/280
https://github.com/hyperoslo/Sync/issues/285
=> Fixed a bug in sync_toManyRelationship referencing the wrong entity.

Source/Sync/Sync.swift
In order to user `Sync.changes` with setting operations (e.g. only insert) the operations should be public to be used.
=> Updated Operation visibility

Demo.xcodeproj/project.pbxproj, Source/Sync/Sync.swift, Tests/Sync/SyncDelegateTests.swift
Let's you change the structure of the JSON before returning it.
This could be used for cleaning up dates and so on, here I'm using it to make sure that every insert gets a localID.
```swift
func sync(_ sync: Sync, willInsert json: [String: Any], in entityNamed: String) -> [String: Any] {
var newJSON = json
newJSON["localID"] = UUID().uuidString
return newJSON
}
```
=> Intercept inserted JSON

Demo.xcodeproj/project.pbxproj, Tests/Sync/JSONs/233-order-a.json, Tests/Sync/JSONs/233-order-b.json, Tests/Sync/JSONs/233-slides.json, Tests/Sync/Models/233.xcdatamodeld/233.xcdatamodel/contents, Tests/Sync/SyncTests.swift
This PR includes minor updates to the test case for #233.
First way to solve the issue itself might be to update the `guard` in `sync_toManyRelationshipUsingIDsInsteadOfDictionary` to:
guard insertedItems.count > 0 || deletedItems.count > 0 || (insertedItems.count == 0 && deletedItems.count == 0 && relationship.isOrdered) else { return }
and find a way to update the `localItems` without using `insertedItems` and `deletedItems` since they are both empty. 
A solution for syncing the order when items are added as well might prove easier. But I suppose both ways should be covered.
=> Improved test on fix/#233

Source/Sync/Sync.swift, Tests/Sync/NSPersistentContainerTests.swift
Sometimes I do not want to use all operations, I noticed there was no changes() function using a NSPersistentContainer where I could specify them. Added them here.
=> Allow setting the operations when using an NSPersistentContainer

Source/Sync/Sync.swift, Tests/Sync/NSPersistentContainerTests.swift
* Allow setting the operations when making changes using an NSPersistentContainer.
* Use original Sync.changes() with NSPersistentContainer as a wrapper.
* Remove erroneous parent argument.
* Resolve ambiguous test case call due to adding extra function signature.
=> Allow setting the operations when using an NSPersistentContainer (#329)

README.md, Source/NSEntityDescription-SyncPrimaryKey/NSEntityDescription+SyncPrimaryKey.h, Source/NSEntityDescription-SyncPrimaryKey/NSEntityDescription+SyncPrimaryKey.m, Source/NSPropertyDescription-Sync/NSPropertyDescription+Sync.h, Source/NSPropertyDescription-Sync/NSPropertyDescription+Sync.m, Source/Sync/Sync.swift, Tests/NSEntityDescription-SyncPrimaryKey/PrimaryKeyTests.m, Tests/NSEntityDescription-SyncPrimaryKey/SyncPrimaryKey.xcdatamodeld/SyncPrimaryKey.xcdatamodel/contents, Tests/Sync/Models/113.xcdatamodeld/113.xcdatamodel/contents, Tests/Sync/Models/125.xcdatamodeld/125.xcdatamodel/contents, Tests/Sync/Models/151-many-to-many.xcdatamodeld/151-many-to-many.xcdatamodel/contents, Tests/Sync/Models/151-to-many.xcdatamodeld/151-to-many.xcdatamodel/contents, Tests/Sync/Models/157.xcdatamodeld/157.xcdatamodel/contents, Tests/Sync/Models/179.xcdatamodeld/179.xcdatamodel/contents, Tests/Sync/Models/239.xcdatamodeld/239.xcdatamodel/contents, Tests/Sync/Models/277.xcdatamodeld/239.xcdatamodel/contents, Tests/Sync/Models/280.xcdatamodeld/151-many-to-many.xcdatamodel/contents, Tests/Sync/Models/84.xcdatamodeld/84.xcdatamodel/contents, Tests/Sync/Models/Contacts.xcdatamodeld/Demo.xcdatamodel/contents, Tests/Sync/Models/Markets.xcdatamodeld/Demo.xcdatamodel/contents, Tests/Sync/Models/OrderedSocial.xcdatamodeld/Demo.xcdatamodel/contents, Tests/Sync/Models/Social.xcdatamodeld/Demo.xcdatamodel/contents, Tests/SyncPropertyMapper/Models/140.xcdatamodeld/smartworkout.xcdatamodel/contents, Tests/SyncPropertyMapper/Models/Model.xcdatamodeld/Model.xcdatamodel/contents
Rename `hyper.isPrimaryKey` to `sync.isPrimaryKey` while maintaining compatibility so no changes are needed in existing implementations.
=> Rename hyper.isPrimaryKey to sync.isPrimaryKey

README.md, Source/NSManagedObject-SyncPropertyMapper/NSManagedObject+SyncPropertyMapperHelpers.h, Source/NSManagedObject-SyncPropertyMapper/README.md, Source/NSManagedObject-SyncPropertyMapper/SyncPropertyMapper.m, Source/NSPropertyDescription-Sync/NSPropertyDescription+Sync.h, Source/NSPropertyDescription-Sync/NSPropertyDescription+Sync.m, Tests/Sync/NSPropertyDescription+SyncTests.swift, Tests/SyncPropertyMapper/Models/112.xcdatamodeld/hypbug.xcdatamodel/contents, Tests/SyncPropertyMapper/Models/123.xcdatamodeld/Model.xcdatamodel/contents, Tests/SyncPropertyMapper/Models/137.xcdatamodeld/hypbug.xcdatamodel/contents
Renames hyper.nonExportable to sync.nonExportable, while maintaining compatibility for both keys.
=> Rename hyper.nonExportable to sync.nonExportable

Demo.xcodeproj/project.pbxproj, Source/NSManagedObject-SyncPropertyMapper/NSManagedObject+Export.swift, Source/NSManagedObject-SyncPropertyMapper/SyncPropertyMapper.h, Source/NSManagedObject-SyncPropertyMapper/SyncPropertyMapper.m, Tests/SyncPropertyMapper/ExportTests.swift
Again, keeps the old functionality to not break existing apps.
Usage:
```swift
let json = user.export()
```
=> Rename hyp_dictionary to export

Demo.xcodeproj/project.pbxproj, Source/Sync/Sync+ObjC.swift
Hi, @3lvis 
I have added enums to solve the problem in Objective-C. 
I found that Objective-C does not support array of enum as parameter. I mean this
```swift
public class func objc_changes(_ changes: [[String: Any]], inEntityNamed entityName: String, predicate: NSPredicate?, dataStack: DataStack, operations: [ObjcOperationOptions], completion: ((_ error: NSError?) -> Void)?) {
}
```
cannot work.
Thus, I have listed all possible combinations in the new enum.
```swift
@objc public enum ObjcOperationOptions: Int {
case insert = 0
case update = 1
case delete = 2
case insertUpdate = 3
case insertDelete = 4
case updateDelete = 5
case all = 6
}
```
=> Objective-C support for Sync.changes methods.

Source/DataStack/DataStack.swift
iOS 9's `destroyPersistentStore` seems a bit buggy, this PR goes back to the old way of dropping the database.
=> Rollback to old way of restoring persistent store

Source/DateParser/NSDate+PropertyMapper.m, Tests/DateParser/DateTests.swift
Fixed issue in NSDateParser where the date format containing upto micro second is mapped  upto micro seconds  precision in core data
=> NSDateParser containing upto micro second is mapped upto micro seconds precision in core data

Source/Sync/NSManagedObject+Sync.swift
This PR allows nested keys which are tied to relationships to function properly.  For example:
```
note : {
id: 1
relationships: {
authors: {
data: [ 
...authors here...
]
}
}
}
```
sync.remoteKey = relationships.authors.data
=> Nested json keys on relationships work

Source/DateParser/NSDate+PropertyMapper.m, Tests/DateParser/DateTests.swift
=> Fix for date with centiseconds

Source/DateParser/NSDate+PropertyMapper.m, Tests/DateParser/DateTests.swift
Added support for date format with milliseconds but no Z terminator: 2017-12-22T18:10:14.070
=> Support for date format with milliseconds but no Z terminator

Source/DataStack/DataStack.swift, Sync.podspec
Hey @3lvis I am seeing an odd issue when using a disposable context combined with Sync syncing a background context. 
What's happening is I have a disposable context that never has save called on it. It creates a temporary object that is just used to create a request. When that request returns it kicks off Sync which creates a background context. 
I have spend a ton of time trying to track it down but for some reason when the background context is saved it causes the newDisposableMainContextWillSave to be triggered even though the observer was never set on the background context. This causes the background context which data I actually want to be stored to be reset and lost.
I also tried to create a unit test to reproduce this with no success. The even stranger part is it doesn't happen …
=> Checking that the context that is being rest for a disposable context is indeed a disposable context

Source/DataStack/DataStack.swift, Tests/DataFilter/DataFilterTests.swift, Tests/DataStack/Tests.swift, Tests/Sync/Helpers/Helper.swift, Tests/Sync/NSManagedObjectContext+SyncTests.swift
This PR addresses https://github.com/3lvis/Sync/issues/586
These are breaking changes in that they return optional values from initializers instead of explicitly unwrapping the model objects. We should test these properly!
=> Optional initialization
